apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    name: node-app
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: node-app
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: node-app
    spec:
      containers:
      - image: jelmstrom/node-app:latest
        imagePullPolicy: IfNotPresent
        name: node-app
        ports:
        - containerPort: 3000
          protocol: TCP
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: node-app
  type: NodePort


---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-app-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: cgw.kube.com
    http:
      paths:
      - path: /node-app
        backend:
          serviceName: node-app
          servicePort: 3000
