apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/scrape: true
    prometheus.io/port : 3000
  name: node-app-pod
spec:
  containers:
    - name: node-pod
      image: jelmstrom/node-app:latest