apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: true
  labels:
    name: node-app
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: node-app
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: node-app
    spec:
      containers:
      - image: jelmstrom/node-app:latest
        imagePullPolicy: IfNotPresent
        name: node-app
        ports:
        - containerPort: 3000
          protocol: TCP
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
kind: Service
metadata:
  name: node-app
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: node-app
  type: NodePort
